### ISSUE TITLE
ModuleNotFoundError: No module named 'viconnexusapi'

### ISSUE THREAD

**Issue by omian** [pyCGM2/pyCGM2#43]
Hello,

I have used instructions on the following page to create a virtual environment in miniconda containing Python 3.9 and PyCGM2. 
https://pycgm2.netlify.app/installation/pycgm2_installation/

I used the alternative installation method described on that page as 'conda install -c pycgm2 pycgm2' approach did not work.

I then tried to follow the quickstart instructions on the following page for Vicon users:
https://pycgm2.netlify.app/nexusqualisys/

However, when I try to run pyCGM2.exe I get a ModuleNotFoundError referencing 'viconnexusapi'.
For example, here is the full traceback when I try to run pyCGM2.exe -h 

```
Traceback (most recent call last):
  File "C:\Users\Omar\miniconda3\envs\pycgm39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Omar\miniconda3\envs\pycgm39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Omar\miniconda3\envs\pycgm39\Scripts\pyCGM2.exe\__main__.py", line 4, in <module>
  File "C:\Users\Omar\miniconda3\envs\pycgm39\lib\site-packages\pyCGM2\Apps\Commands\rullThemAllCommands.py", line 12, in <module>
    from pyCGM2.Apps.ViconApps.CGM2_3 import CGM2_3_Calibration, CGM2_3_Fitting
  File "C:\Users\Omar\miniconda3\envs\pycgm39\lib\site-packages\pyCGM2\Apps\ViconApps\CGM2_3\CGM2_3_Calibration.py", line 18, in <module>
    from viconnexusapi import ViconNexus
ModuleNotFoundError: No module named 'viconnexusapi'
```

Is there something I need to do to get this working beyond what's described on the pages above? 

Thanks

Omar

**Comment by aaa34169** [comment]
solved and integrated in the master branch or the pre release 4.4.0rc1
